LICENSE.txt
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Kcu1500Hsio.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Root.py
shared/ruckus.tcl

- preformed `git merge origin/pre-release`
- Update LICENSE.txt for year 2020
- Add missing parameters to pyrogue.Root.__init__() #10
- But this _Core.py is removed as part of timestamp-dev branch
- updating submodules locks
- specifically updating lcls-timing-core lock to future v3.0.0 release
- adding l2si-core lock to future v2.0.0 release
- updating surf to future v2.0.4 release
- error checking for PGP_TYPE_G in firmware
- updating from axi.AxiStreamMonitoring to axi.AxiStreamMonAxiL in software
- changing arg from driverPath to dev in software

Timestamp dev patch

---

python/lcls2_pgp_fw_lib/hardware/shared/_TimingRx.py

Some Variable types changes in l2si-core v3.0.0 requiring updates to Rogue code here for compatibility.

Update for l2si-core v3.0.0

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd

Pass clearReadout signal up through the hierarchy.
This branch also contains #18 so that should be merged first.

Clear readout

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd
python/lcls2_pgp_fw_lib/hardware/shared/_TimingPhyMonitor.py
shared/rtl/TimingPhyMonitor.vhd

Currently untested. I think we want a similar thing on the Rx. It's not clear to me why the current resets don't always work. This needs a bit of testing in real hardware yet.

Add software reset register for Timing Tx PHY

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd
python/lcls2_pgp_fw_lib/hardware/shared/_TimingPhyMonitor.py
shared/rtl/Pgp2bLane.vhd
shared/rtl/Pgp3Lane.vhd
shared/rtl/TimingPhyMonitor.vhd

1. #19 - Add software reset register for Timing Tx PHY
1. #18 - Send Trigger Tags
1. #20 - Clear readout

Release Candidate v3.1.0

---

shared/ruckus.tcl

release candidate v3.2.0

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/SlacPgpCardG4/ruckus.tcl
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd
hardware/XilinxKcu1500/ruckus.tcl
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/_SlacPgpCardG4Hsio.py
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/_SlacPgpCardG4TimingRx.py
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/__init__.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Kcu1500Hsio.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Kcu1500TimingRx.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/__init__.py
python/lcls2_pgp_fw_lib/hardware/__init__.py
python/lcls2_pgp_fw_lib/hardware/shared/_Hsio.py
python/lcls2_pgp_fw_lib/hardware/shared/_RogueStreams.py
python/lcls2_pgp_fw_lib/hardware/shared/_Root.py
python/lcls2_pgp_fw_lib/hardware/shared/_TimingPhyMonitor.py
python/lcls2_pgp_fw_lib/hardware/shared/_TimingRx.py
releaseNotes.py
setup.py
shared/rtl/Pgp2bLane.vhd
shared/rtl/Pgp3Lane.vhd
shared/rtl/PgpLaneRx.vhd
shared/rtl/PgpLaneTx.vhd
shared/rtl/TimingPhyInit.vhd
shared/rtl/TimingPhyMonitor.vhd
shared/ruckus.tcl

This PR adds KCU1500 support for https://github.com/slaclab/l2si-core/pull/25, which allows `TriggerEventManager` to handle LCLS-I timing.

TriggerEvent modules for EVR Timing

---

python/lcls2_pgp_fw_lib/hardware/shared/_TimingRx.py

Update the commands that switch between LCLS-I and LCLS-II timing. 
Add command to switch to TpgMiniStream timing.

Update Timing Mode Commands

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/SlacPgpCardG4/ruckus.tcl
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd
hardware/XilinxKcu1500/ruckus.tcl
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/_SlacPgpCardG4Hsio.py
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/_SlacPgpCardG4TimingRx.py
python/lcls2_pgp_fw_lib/hardware/SlacPgpCardG4/__init__.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Kcu1500Hsio.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/_Kcu1500TimingRx.py
python/lcls2_pgp_fw_lib/hardware/XilinxKcu1500/__init__.py
python/lcls2_pgp_fw_lib/hardware/__init__.py
python/lcls2_pgp_fw_lib/hardware/shared/_Hsio.py
python/lcls2_pgp_fw_lib/hardware/shared/_RogueStreams.py
python/lcls2_pgp_fw_lib/hardware/shared/_Root.py
python/lcls2_pgp_fw_lib/hardware/shared/_TimingPhyMonitor.py
python/lcls2_pgp_fw_lib/hardware/shared/_TimingRx.py
releaseNotes.py
setup.py
shared/rtl/Pgp2bLane.vhd
shared/rtl/Pgp3Lane.vhd
shared/rtl/PgpLaneRx.vhd
shared/rtl/PgpLaneTx.vhd
shared/rtl/TimingPhyInit.vhd
shared/rtl/TimingPhyMonitor.vhd
shared/ruckus.tcl

- TriggerEvent modules for EVR Timing #23
- Update Timing Mode Commands #26
- Bugfix for timing mode switch commands #27

Release Candidate v3.3.0

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd

Depends upon l2si-core pull request #33.

Add valid and rden signals for timing message cache

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd

1. #28 - Add valid and rden signals for timing message cache

Release Candidate v3.4.0

---

python/lcls2_pgp_fw_lib/hardware/shared/_TimingPhyMonitor.py
python/lcls2_pgp_fw_lib/hardware/shared/_TimingRx.py

- updating TimingPhyMonitor.CntRst from register to command 
- Increasing wait for timing to become stable from 0.1 s to 1.0

Updates to TimingPhyMonitor and  TimingRx

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd

- bug fix for PGPv3 @ 6.25 Gb/s

Release Candidate v3.5.1

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4TimingRx.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500TimingRx.vhd
shared/ruckus.tcl

- Add AXI stream timing stream information to event #35
- Updating submodule locks to latest tag releases
- renamed `eventAxis*` interfaces to `eventTrigMsg*` interfaces

Release Candidate v4.0.0

---

hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/SlacPgpCardG4/ruckus.tcl
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/ruckus.tcl
shared/rtl/TimingRx.vhd

- switching to PGP4 link rate to 6.25Gb/s because of layout issues on FEB board

Release Candidate v5.1.0

---

python/lcls2_pgp_fw_lib/shared/_Hsio.py
python/lcls2_pgp_fw_lib/shared/_Root.py
python/lcls2_pgp_fw_lib/shared/_TimingRx.py

- Changes that were required for https://github.com/slaclab/cameralink-gateway/pull/31

adding per lane (mixed camera) support 

---

python/lcls2_pgp_fw_lib/shared/_Hsio.py
python/lcls2_pgp_fw_lib/shared/_Root.py
python/lcls2_pgp_fw_lib/shared/_TimingRx.py

- adding per lane (mixed camera) support #39

Release Candidate v5.2.0

---

shared/ruckus.tcl

- updating submodule lock for l2si-core to v3.3.2
- https://github.com/slaclab/l2si-core/pull/44

Release Candidate v5.2.1

---

python/lcls2_pgp_fw_lib/shared/_Hsio.py

- updating python Pgp2bAxi's statusCountBits & errorCountBits

Release Candidate v5.2.2

---

hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxKcu1500/xdc/Kcu1500Hsio.xdc
shared/rtl/TimingRx.vhd

- using KCU1500.userClk156 (instead of userClk25) to create the 371 MHz clock

Release Candidate v5.4.0

---

.flake8
.github/workflows/lcls2_pgp_ci.yml
LICENSE.txt
hardware/XilinxVariumC1100/xdc/C1100Hsio.xdc
python/lcls2_pgp_fw_lib/shared/_TimingRx.py
setup.py

- [adding numDetectors arg to TimingRx.py](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/e1dc464fbb4ca11f923a1aabd2afeb0d0eebf177)
- [Update .flake8](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/8a8afeb09f145009569c55a6807385f8f214c92f)
- [2023 LICENSE.txt update](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/48e2f89586a323a3866d6db1a0a196e28b4f2123)
- [.XDC bug fix](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/b512ee8793254a7a4e6713cfca82dfd276513ecf)

Release Candidate v5.4.1

---

.github/workflows/lcls2_pgp_ci.yml
hardware/XilinxVariumC1100/rtl/C1100Hsio.vhd
hardware/XilinxVariumC1100/xdc/Pgp2bTiming.xdc
shared/rtl/UltraScale+/Pgp2bLane.vhd

- [Update lcls2_pgp_ci.yml](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/a3459b66362d8e5810d6319650bd8df300c4442b)
- [adding support for XilinxVariumC1100 with PGP2b](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/1c5c7e203143981fa1430f793f81f6383ffbd5a1)

Release Candidate v5.8.0

---

python/lcls2_pgp_fw_lib/shared/_Application.py

- adding ApplicationLaneConfigDict class to _Application.py

Release Candidate v5.9.1

---

shared/rtl/UltraScale+/TimingRx.vhd
shared/rtl/UltraScale/TimingRx.vhd

- bug fix to prevent locked up gtRxClk/gtRxRst

Release Candidate v5.9.2

---

LICENSE.txt
conda-recipe/meta.yaml
hardware/SlacPgpCardG4/rtl/SlacPgpCardG4Hsio.vhd
hardware/XilinxKcu1500/rtl/Kcu1500Hsio.vhd
hardware/XilinxVariumC1100/rtl/C1100Hsio.vhd
shared/rtl/UltraScale+/Pgp2bLane.vhd
shared/rtl/UltraScale+/Pgp4Lane.vhd
shared/rtl/UltraScale/Pgp2bLane.vhd
shared/rtl/UltraScale/Pgp4Lane.vhd

- [whitespace removal](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/22149083e0adaac90cf890b9c979a504e37a4d5d)
- [Update LICENSE.txt](https://github.com/slaclab/lcls2-pgp-fw-lib/pull/55/commits/1d763ade375b488f1e553b127134c48f9e73fff4)
- [adding triggerPause feature](https://github.com/slaclab/lcls2-pgp-fw-lib/pull/55/commits/ee6e5727853c3260f76bc26aca86390cd95fedab)

Release Candidate v5.10.0

---

.github/workflows/lcls2_pgp_ci.yml
LICENSE.txt
python/lcls2_pgp_fw_lib/shared/_TimingRx.py
shared/rtl/UltraScale+/TimingRx.vhd
shared/rtl/UltraScale/TimingRx.vhd

- [migrating CI from ubuntu-22.04 to ubuntu-24.04](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/ed1f152d6531acb24a5f4cc717433f5657715de2)
- [Update LICENSE.txt](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/c111d56506f1e4e8d8aecc96f521713d5849fe6a)
- [bug fix to prevent latch when EN_LCLS_I_TIMING_G=false & EN_LCLS_II_TIMING_G=true](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/9ac1076b2ba1dfbd538762e0a24a2c695b3b6223)
- [adding 1sec sleep between TimingFrameRx.C_RxReset() & TimingPhyMonitor.RxUserRst()](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/21b4970e1fd8c04115287e8ff5767f41f731a086)

Release Candidate v5.13.0

---

shared/rtl/TimingPhyMonitor.vhd

- Fix GT reset issue
- set GT in reset by default and wait for mmcm to be locked before releasing it

Release Candidate v5.13.1

---

hardware/SlacPgpCardG4/xdc/SlacPgpCardG4Hsio.xdc
hardware/XilinxKcu1500/xdc/Kcu1500Hsio.xdc
hardware/XilinxVariumC1100/xdc/C1100Hsio.xdc
python/lcls2_pgp_fw_lib/shared/_TimingRx.py
shared/rtl/UltraScale+/TimingRx.vhd
shared/rtl/UltraScale/TimingRx.vhd

- [simplifying the TimingRx's TX MUX topology](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/a775a8db5f4ff9138c9719d540f5239f37f500d8)

Release Candidate v5.13.3

---

README.md
hardware/SlacPgpCardG4/ruckus.tcl
hardware/XilinxKcu1500/ruckus.tcl
hardware/XilinxVariumC1100/ruckus.tcl
shared/ruckus.tcl

- [Update README.md to include DOE Code Reference](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/9f7740c13e40cb3b9cf3e9da649eb5f465365e7f)

Release Candidate v5.13.4

---

python/lcls2_pgp_fw_lib/shared/_TimingRx.py
shared/rtl/UltraScale+/TimingRx.vhd
shared/rtl/UltraScale/TimingRx.vhd

- [recoding to remove the inferred latches](https://github.com/slaclab/lcls2-pgp-fw-lib/commit/d068b774b628bef1d4fbf99d17fce3f12bca2765)
- [overhauling the ConfigLclsTiming() functions to remove sleep statements in init sequence](https://github.com/slaclab/lcls2-pgp-fw-lib/pull/69/commits/8149d3e6cb6f544f05b48c9ef746233f934d4a2c)

Release Candidate v5.13.6
